# Generated by Django 4.1.3 on 2022-12-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFredy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermanos',
            name='apellido',
            field=models.IntegerField(max_length=15),
        ),
    ]
